apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    app: nginxpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginxport
      nodePort: 31010
  type: NodePort
