apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-health-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-health
  template:
    metadata:
      labels:
        app: nginx-health
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

          # STARTUP PROBE
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30   # 30 * 10s = 300s max startup time
            periodSeconds: 10

          # LIVENESS PROBE
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          # READINESS PROBE
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
