apiVersion: v1
kind: Pod
metadata:
  name: application-pod
spec:
  initContainers:
    - name: simple-init
      image: busybox:latest
      command:
        - sh
        - -c
        - "echo Init container done; sleep 2"
  containers:
    - name: main-app
      image: busybox:latest
      command:
        - sh
        - -c
        - "echo Main container started; sleep 3600"
